version: '3.8'

services:
  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: manabi_nginx
    restart: unless-stopped
    ports:
      - "8888:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

  # PHP-FPM Service
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: manabi_php
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html
    environment:
      - "DB_HOST=mysql"
      - "DB_PORT=3306"
      - "DB_DATABASE=manabi_link"
      - "DB_USERNAME=manabi"
      - "DB_PASSWORD=123qwecc"

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: manabi_mysql
    restart: unless-stopped
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: manabi_link
      MYSQL_USER: manabi
      MYSQL_PASSWORD: 123qwecc
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./docker/data/mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - "8008:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

  # Node Service for NPM commands
  npm:
    image: node:18-alpine
    container_name: manabi_npm
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    entrypoint: ['npm']

networks:
  default:
    driver: bridge