import type { Metadata } from 'next';
import './globals.css';
export const metadata: Metadata = {
    title: 'My New App',
    description: 'Generated by Onlook',
};
export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en" data-oid="96o_t:_">
            <body className="h-[1102px]" data-oid="ndc-vm-">
                {children}
            </body>
        </html>
    );
}
